// angular-app/src/app/shared/run-row.component.ts
import { Component, Input } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Router } from '@angular/router'
import { LucideAngularModule, GitBranch, ExternalLink } from 'lucide-angular'
import { BadgeComponent } from './badge.component'
import { formatRelativeTime, calculateDuration, formatSha, truncate } from '../core/utils'
import type { WorkflowRun } from '../core/types'

@Component({
  selector: 'app-run-row',
  standalone: true,
  imports: [CommonModule, LucideAngularModule, BadgeComponent],
  template: `
    <tr (click)="goto()" class="hover:bg-zinc-50 transition-colors cursor-pointer">
      <td *ngIf="showWorkflow" class="py-3 px-4 text-sm">
        <span class="font-medium text-zinc-800">{{ truncate(run.workflow_name || ('Run #' + run.github_run_id), 40) }}</span>
      </td>
      <td *ngIf="showRepo" class="py-3 px-4 text-sm text-zinc-500">{{ run.repo_name || '—' }}</td>
      <td class="py-3 px-4">
        <span class="inline-flex items-center gap-1 text-xs text-zinc-500">
          <lucide-angular [img]="icons.GitBranch" [size]="11" class="text-zinc-400"></lucide-angular>
          <span class="truncate max-w-[120px]">{{ run.branch }}</span>
        </span>
      </td>
      <td class="py-3 px-4">
        <code class="text-xs text-zinc-400 font-mono bg-zinc-50 px-1.5 py-0.5 rounded">{{ formatSha(run.head_sha) }}</code>
      </td>
      <td class="py-3 px-4">
        <app-badge [status]="displayStatus()"></app-badge>
      </td>
      <td class="py-3 px-4 text-xs text-zinc-500 tabular-nums">
        {{ run.started_at ? calculateDuration(run.started_at, run.completed_at) : '—' }}
      </td>
      <td class="py-3 px-4 text-xs text-zinc-400">
        {{ run.started_at ? formatRelativeTime(run.started_at) : '—' }}
      </td>
      <td class="py-3 px-4">
        <a *ngIf="run.html_url" [href]="run.html_url" target="_blank" rel="noopener noreferrer" (click)="$event.stopPropagation()" class="text-zinc-400 hover:text-amber-600 transition-colors">
          <lucide-angular [img]="icons.ExternalLink" [size]="13"></lucide-angular>
        </a>
      </td>
    </tr>
  `,
})
export class RunRowComponent {
  @Input({ required: true }) run!: WorkflowRun
  @Input() showWorkflow = true
  @Input() showRepo = true

  icons = { GitBranch, ExternalLink }
  truncate = truncate
  formatSha = formatSha
  calculateDuration = calculateDuration
  formatRelativeTime = formatRelativeTime

  constructor(private router: Router) {}

  displayStatus(): string {
    return this.run.status === 'completed' ? this.run.conclusion || 'neutral' : this.run.status
  }

  goto() {
    this.router.navigate(['/runs', this.run.id])
  }
}

// src/components/workflows/run-row.tsx
'use client'

import { useRouter } from 'next/navigation'
import { GitBranch, ExternalLink } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { formatRelativeTime, calculateDuration, formatSha, truncate } from '@/lib/utils'
import { cn } from '@/lib/utils'
import type { WorkflowRun } from '@/types'

interface RunRowProps {
  run: WorkflowRun
  showWorkflow?: boolean
  showRepo?: boolean
  className?: string
}

export function RunRow({ run, showWorkflow = true, showRepo = true, className }: RunRowProps) {
  const router = useRouter()
  const displayStatus =
    run.status === 'completed' ? (run.conclusion ?? 'neutral') : run.status

  return (
    <tr
      onClick={() => router.push(`/runs/${run.id}`)}
      className={cn('hover:bg-zinc-50 transition-colors cursor-pointer', className)}
    >
      {showWorkflow && (
        <td className="py-3 px-4 text-sm">
          <span className="font-medium text-zinc-800">
            {truncate(run.workflow_name ?? `Run #${run.github_run_id}`, 40)}
          </span>
        </td>
      )}
      {showRepo && (
        <td className="py-3 px-4 text-sm text-zinc-500">
          {run.repo_name ?? '—'}
        </td>
      )}
      <td className="py-3 px-4">
        <span className="inline-flex items-center gap-1 text-xs text-zinc-500">
          <GitBranch size={11} className="text-zinc-400" />
          <span className="truncate max-w-[120px]">{run.branch}</span>
        </span>
      </td>
      <td className="py-3 px-4">
        <code className="text-xs text-zinc-400 font-mono bg-zinc-50 px-1.5 py-0.5 rounded">
          {formatSha(run.head_sha)}
        </code>
      </td>
      <td className="py-3 px-4">
        <Badge status={displayStatus} />
      </td>
      <td className="py-3 px-4 text-xs text-zinc-500 tabular-nums">
        {run.started_at ? calculateDuration(run.started_at, run.completed_at) : '—'}
      </td>
      <td className="py-3 px-4 text-xs text-zinc-400">
        {run.started_at ? formatRelativeTime(run.started_at) : '—'}
      </td>
      <td className="py-3 px-4">
        {run.html_url && (
          <a
            href={run.html_url}
            target="_blank"
            rel="noopener noreferrer"
            onClick={(e) => e.stopPropagation()}
            className="text-zinc-400 hover:text-amber-600 transition-colors"
          >
            <ExternalLink size={13} />
          </a>
        )}
      </td>
    </tr>
  )
}
