// src/app/(dashboard)/analytics/page.tsx
'use client'

import {
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from 'recharts'
import { TrendingUp, Bot, CheckCircle2, AlertCircle } from 'lucide-react'
import { useAnalytics } from '@/hooks/useAnalytics'
import { StatsCard } from '@/components/dashboard/stats-card'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { SkeletonCard } from '@/components/ui/skeleton'
import { PageHeader } from '@/components/ui/page-header'

function CustomTooltip({
  active,
  payload,
  label,
}: {
  active?: boolean
  payload?: Array<{ color: string; name: string; value: number }>
  label?: string
}) {
  if (!active || !payload || payload.length === 0) return null
  return (
    <div className="bg-white border border-zinc-200 rounded-lg shadow-lg p-3 text-xs">
      <p className="font-semibold text-zinc-700 mb-2">{label}</p>
      {payload.map((entry) => (
        <div key={entry.name} className="flex items-center gap-2">
          <span
            className="w-2 h-2 rounded-full flex-shrink-0"
            style={{ backgroundColor: entry.color }}
          />
          <span className="text-zinc-500 capitalize">{entry.name}:</span>
          <span className="font-semibold text-zinc-800">{entry.value}</span>
        </div>
      ))}
    </div>
  )
}

function formatDuration(seconds: number | null | undefined): string {
  if (seconds == null) return '—'
  if (seconds < 60) return `${Math.round(seconds)}s`
  const m = Math.floor(seconds / 60)
  const s = Math.round(seconds % 60)
  if (m < 60) return s ? `${m}m ${s}s` : `${m}m`
  const h = Math.floor(m / 60)
  return `${h}h ${m % 60}m`
}

export default function AnalyticsPage() {
  const { data: analytics, isLoading, error } = useAnalytics()

  const completed = analytics?.completed_runs ?? 0
  const successPct = completed ? (analytics!.success_count / completed) * 100 : 0
  const failurePct = completed ? (analytics!.failure_count / completed) * 100 : 0
  const otherPct = completed ? (analytics!.other_count / completed) * 100 : 0

  const successRateDisplay = analytics && completed ? `${successPct.toFixed(1)}%` : '—'
  const failureRateDisplay = analytics && completed ? `${failurePct.toFixed(1)}%` : '—'

  return (
    <div className="p-8">
      <PageHeader
        eyebrow="Overview"
        title="Analytics"
        description="Pipeline performance metrics and AI remediation insights."
      />

      {}
      {error && (
        <div className="flex items-center gap-3 text-rose-600 bg-rose-50 border border-rose-200 rounded-lg p-4 mb-6">
          <AlertCircle size={16} />
          <p className="text-sm">Failed to load analytics data.</p>
        </div>
      )}

      {}
      <div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-8">
        {isLoading ? (
          [...Array(4)].map((_, i) => <SkeletonCard key={i} />)
        ) : (
          <>
            <StatsCard
              title="Total Runs"
              value={analytics?.total_runs ?? 0}
              icon={TrendingUp}
            />
            <StatsCard
              title="Success Rate"
              value={successRateDisplay}
              icon={CheckCircle2}
              iconClassName="bg-emerald-50"
            />
            <StatsCard
              title="Failure Rate"
              value={failureRateDisplay}
              icon={AlertCircle}
              iconClassName="bg-rose-50"
            />
            <StatsCard
              title="AI PRs Raised"
              value={analytics?.remediations_raised ?? 0}
              icon={Bot}
              iconClassName="bg-amber-50"
            />
          </>
        )}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6 mb-6">
        {}
        <Card>
          <CardHeader>
            <CardTitle>Run Trend — Last 30 Days</CardTitle>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="h-64 flex items-center justify-center">
                <div className="w-full h-full bg-zinc-50 rounded animate-pulse" />
              </div>
            ) : !analytics?.run_trend || analytics.run_trend.length === 0 ? (
              <div className="h-64 flex items-center justify-center text-zinc-400 text-sm">
                No trend data available yet.
              </div>
            ) : (
              <ResponsiveContainer width="100%" height={260}>
                <LineChart
                  data={analytics.run_trend}
                  margin={{ top: 4, right: 4, bottom: 0, left: -20 }}
                >
                  <CartesianGrid strokeDasharray="3 3" stroke="#f4f4f5" />
                  <XAxis
                    dataKey="date"
                    tick={{ fontSize: 11, fill: '#a1a1aa' }}
                    tickLine={false}
                    axisLine={{ stroke: '#e4e4e7' }}
                    tickFormatter={(v: string) => {
                      const d = new Date(v)
                      return `${d.getMonth() + 1}/${d.getDate()}`
                    }}
                  />
                  <YAxis
                    tick={{ fontSize: 11, fill: '#a1a1aa' }}
                    tickLine={false}
                    axisLine={false}
                  />
                  <Tooltip content={<CustomTooltip />} />
                  <Legend
                    iconType="circle"
                    iconSize={8}
                    wrapperStyle={{ fontSize: '11px', paddingTop: '12px' }}
                  />
                  <Line
                    type="monotone"
                    dataKey="success"
                    stroke="#10b981"
                    strokeWidth={2}
                    dot={false}
                    name="Success"
                  />
                  <Line
                    type="monotone"
                    dataKey="failed"
                    stroke="#f43f5e"
                    strokeWidth={2}
                    dot={false}
                    name="Failed"
                  />
                </LineChart>
              </ResponsiveContainer>
            )}
          </CardContent>
        </Card>

        {}
        <Card>
          <CardHeader>
            <CardTitle>Top Failing Repositories</CardTitle>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="h-64 bg-zinc-50 rounded animate-pulse" />
            ) : !analytics?.top_failing_repos ||
              analytics.top_failing_repos.length === 0 ? (
              <div className="h-64 flex items-center justify-center text-zinc-400 text-sm">
                <div className="text-center">
                  <CheckCircle2 size={32} className="text-emerald-300 mx-auto mb-3" />
                  <p>No failing repos. Great work!</p>
                </div>
              </div>
            ) : (
              <ResponsiveContainer width="100%" height={260}>
                <BarChart
                  data={analytics.top_failing_repos}
                  layout="vertical"
                  margin={{ top: 4, right: 20, bottom: 0, left: 0 }}
                >
                  <CartesianGrid
                    strokeDasharray="3 3"
                    horizontal={false}
                    stroke="#f4f4f5"
                  />
                  <XAxis
                    type="number"
                    tick={{ fontSize: 11, fill: '#a1a1aa' }}
                    tickLine={false}
                    axisLine={{ stroke: '#e4e4e7' }}
                  />
                  <YAxis
                    dataKey="repo"
                    type="category"
                    width={100}
                    tick={{ fontSize: 11, fill: '#52525b' }}
                    tickLine={false}
                    axisLine={false}
                    tickFormatter={(v: string) =>
                      v.length > 16 ? v.slice(0, 16) + '…' : v
                    }
                  />
                  <Tooltip content={<CustomTooltip />} />
                  <Bar
                    dataKey="count"
                    fill="#f59e0b"
                    radius={[0, 4, 4, 0]}
                    name="Failures"
                  />
                </BarChart>
              </ResponsiveContainer>
            )}
          </CardContent>
        </Card>
      </div>

      {}
      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Run Outcomes ({completed.toLocaleString()} completed)</CardTitle>
        </CardHeader>
        <CardContent>
          {completed === 0 ? (
            <p className="text-sm text-zinc-400 py-2">No completed runs yet.</p>
          ) : (
            <>
              <div className="flex h-3 w-full overflow-hidden rounded-full bg-zinc-100">
                <div className="bg-emerald-500" style={{ width: `${successPct}%` }} />
                <div className="bg-rose-500" style={{ width: `${failurePct}%` }} />
                <div className="bg-zinc-300" style={{ width: `${otherPct}%` }} />
              </div>
              <div className="mt-3 flex flex-wrap gap-6 text-xs text-zinc-500">
                <span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-emerald-500" />Success {successPct.toFixed(1)}% ({analytics?.success_count ?? 0})</span>
                <span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-rose-500" />Failure {failurePct.toFixed(1)}% ({analytics?.failure_count ?? 0})</span>
                <span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-zinc-300" />Other {otherPct.toFixed(1)}% ({analytics?.other_count ?? 0})</span>
              </div>
              <p className="mt-2 text-[11px] text-zinc-400">&ldquo;Other&rdquo; = cancelled, skipped, timed-out or startup-failure runs.</p>
            </>
          )}
        </CardContent>
      </Card>

      {}
      <Card>
        <CardHeader>
          <CardTitle>AI Remediation</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center gap-8 py-4">
            <div className="text-center">
              <p className="text-3xl font-bold text-zinc-800 tabular-nums">
                {analytics?.remediations_raised ?? 0}
              </p>
              <p className="text-xs text-zinc-500 mt-1">PRs raised</p>
            </div>
            <div className="w-px h-12 bg-zinc-100" />
            <div className="text-center">
              <p className="text-3xl font-bold text-zinc-800 tabular-nums">
                {formatDuration(analytics?.avg_analysis_seconds)}
              </p>
              <p className="text-xs text-zinc-500 mt-1">Avg. time to fix suggestion</p>
            </div>
            <div className="w-px h-12 bg-zinc-100" />
            <div className="text-center">
              <p className="text-3xl font-bold text-zinc-800 tabular-nums">
                {formatDuration(analytics?.avg_time_to_pr_seconds)}
              </p>
              <p className="text-xs text-zinc-500 mt-1">Avg. time to PR</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// angular-app/src/app/pages/analytics.component.ts
import { Component, OnInit, signal } from '@angular/core'
import { CommonModule } from '@angular/common'
import { LucideAngularModule, TrendingUp, Bot, CheckCircle2, AlertCircle } from 'lucide-angular'
import { PageHeaderComponent } from '../shared/page-header.component'
import { LineChartComponent } from '../shared/line-chart.component'
import { BarChartComponent, BarDatum } from '../shared/bar-chart.component'
import { ApiService } from '../core/api.service'
import type { AnalyticsData } from '../core/types'

function formatDuration(seconds: number | null | undefined): string {
  if (seconds == null) return '—'
  if (seconds < 60) return `${Math.round(seconds)}s`
  const m = Math.floor(seconds / 60)
  const s = Math.round(seconds % 60)
  if (m < 60) return s ? `${m}m ${s}s` : `${m}m`
  const h = Math.floor(m / 60)
  return `${h}h ${m % 60}m`
}

@Component({
  selector: 'app-analytics',
  standalone: true,
  imports: [CommonModule, LucideAngularModule, PageHeaderComponent, LineChartComponent, BarChartComponent],
  templateUrl: './analytics.component.html',
})
export class AnalyticsComponent implements OnInit {
  icons = { TrendingUp, Bot, CheckCircle2, AlertCircle }
  formatDuration = formatDuration

  analytics = signal<AnalyticsData | null>(null)
  isLoading = signal(true)
  error = signal(false)

  constructor(private api: ApiService) {}

  async ngOnInit() {
    try {
      this.analytics.set(await this.api.fetchAnalytics())
    } catch {
      this.error.set(true)
    } finally {
      this.isLoading.set(false)
    }
  }

  completed(): number {
    return this.analytics()?.completed_runs ?? 0
  }

  successPct(): number {
    const a = this.analytics()
    return a && this.completed() ? (a.success_count / this.completed()) * 100 : 0
  }

  failurePct(): number {
    const a = this.analytics()
    return a && this.completed() ? (a.failure_count / this.completed()) * 100 : 0
  }

  otherPct(): number {
    const a = this.analytics()
    return a && this.completed() ? (a.other_count / this.completed()) * 100 : 0
  }

  topFailingBars(): BarDatum[] {
    return (this.analytics()?.top_failing_repos ?? []).map((r) => ({ label: r.repo, value: r.count }))
  }
}

<div class="p-8">
  <app-page-header eyebrow="Overview" title="Insights" description="Failure, remediation velocity and delivery-health signals across your estate.">
    <!-- Suggested focus: one short AI-generated recommendation from the metrics below. -->
    <div actions *ngIf="suggestionLoading() || suggestion()" class="border border-zinc-200 dark:border-zinc-800 rounded-lg px-3.5 py-2.5 bg-white dark:bg-zinc-900 max-w-xs">
      <p class="text-[10px] font-medium text-zinc-400 uppercase tracking-wider mb-1">Suggested focus</p>
      <div *ngIf="suggestionLoading()" class="h-3.5 w-32 bg-zinc-100 dark:bg-zinc-800 rounded animate-pulse"></div>
      <p *ngIf="!suggestionLoading() && suggestion()" class="text-xs text-zinc-700 dark:text-zinc-300 leading-snug">{{ suggestion() }}</p>
    </div>
  </app-page-header>

  <div *ngIf="error()" class="flex items-center gap-3 text-rose-600 bg-rose-50 border border-rose-200 rounded-lg p-4 mb-6">
    <lucide-angular [img]="icons.AlertCircle" [size]="16"></lucide-angular>
    <p class="text-sm">Failed to load insights data.</p>
  </div>

  <!-- Headline KPIs: failure + remediation velocity -->
  <div class="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-4">
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm p-5">
      <div class="flex items-start justify-between">
        <div class="flex-1 min-w-0">
          <p class="text-xs font-medium text-zinc-500 uppercase tracking-wider">Failure Rate</p>
          <p class="mt-2 text-2xl font-bold text-zinc-800 tabular-nums">{{ completed() ? (failurePct() | number: '1.1-1') + '%' : '—' }}</p>
          <p class="text-[11px] text-zinc-400 mt-1">of {{ completed().toLocaleString() }} completed runs</p>
        </div>
        <div class="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 bg-rose-50">
          <lucide-angular [img]="icons.AlertCircle" [size]="20" class="text-rose-600"></lucide-angular>
        </div>
      </div>
    </div>
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm p-5">
      <div class="flex items-start justify-between">
        <div class="flex-1 min-w-0">
          <p class="text-xs font-medium text-zinc-500 uppercase tracking-wider">MTTR</p>
          <p class="mt-2 text-2xl font-bold text-zinc-800 tabular-nums">{{ formatDuration(analytics()?.mttr_seconds) }}</p>
          <p class="text-[11px] text-zinc-400 mt-1">run failure → fix PR raised</p>
        </div>
        <div class="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 bg-amber-50">
          <lucide-angular [img]="icons.Timer" [size]="20" class="text-amber-600"></lucide-angular>
        </div>
      </div>
    </div>
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm p-5">
      <div class="flex items-start justify-between">
        <div class="flex-1 min-w-0">
          <p class="text-xs font-medium text-zinc-500 uppercase tracking-wider">MTTD</p>
          <p class="mt-2 text-2xl font-bold text-zinc-800 tabular-nums">{{ formatDuration(analytics()?.mttd_seconds) }}</p>
          <p class="text-[11px] text-zinc-400 mt-1">failure → analysis started</p>
        </div>
        <div class="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 bg-sky-50">
          <lucide-angular [img]="icons.Search" [size]="20" class="text-sky-600"></lucide-angular>
        </div>
      </div>
    </div>
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm p-5">
      <div class="flex items-start justify-between">
        <div class="flex-1 min-w-0">
          <p class="text-xs font-medium text-zinc-500 uppercase tracking-wider">PRs Raised</p>
          <p class="mt-2 text-2xl font-bold text-zinc-800 tabular-nums">{{ analytics()?.remediations_raised ?? 0 }}</p>
          <p class="text-[11px] text-zinc-400 mt-1">auto-remediation fixes</p>
        </div>
        <div class="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 bg-amber-50">
          <lucide-angular [img]="icons.Bot" [size]="20" class="text-amber-600"></lucide-angular>
        </div>
      </div>
    </div>
  </div>

  <!-- Secondary signal strip -->
  <div class="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-8">
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm p-5">
      <p class="text-xs font-medium text-zinc-500 uppercase tracking-wider">Total Runs</p>
      <p class="mt-2 text-xl font-bold text-zinc-800 tabular-nums">{{ (analytics()?.total_runs ?? 0).toLocaleString() }}</p>
    </div>
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm p-5">
      <p class="text-xs font-medium text-zinc-500 uppercase tracking-wider">Completed Runs</p>
      <p class="mt-2 text-xl font-bold text-zinc-800 tabular-nums">{{ completed().toLocaleString() }}</p>
    </div>
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm p-5">
      <p class="text-xs font-medium text-zinc-500 uppercase tracking-wider">Run Frequency</p>
      <p class="mt-2 text-xl font-bold text-zinc-800 tabular-nums">{{ (analytics()?.runs_per_day ?? 0) }}<span class="text-sm font-medium text-zinc-400">/day</span></p>
      <p class="text-[11px] text-zinc-400 mt-1">30-day average</p>
    </div>
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm p-5">
      <div class="flex items-start justify-between">
        <div class="flex-1 min-w-0">
          <p class="text-xs font-medium text-zinc-500 uppercase tracking-wider">Open Vulnerabilities</p>
          <p class="mt-2 text-xl font-bold text-zinc-800 tabular-nums">{{ analytics()?.open_vulns_total ?? 0 }}</p>
          <div *ngIf="severityEntries().length" class="mt-2 flex flex-wrap gap-x-3 gap-y-1">
            <span *ngFor="let e of severityEntries()" class="flex items-center gap-1 text-[11px] text-zinc-500">
              <span class="h-1.5 w-1.5 rounded-full" [ngClass]="severityDot(e.sev)"></span>{{ e.sev }} {{ e.count }}
            </span>
          </div>
        </div>
        <div class="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 bg-rose-50">
          <lucide-angular [img]="icons.Bug" [size]="20" class="text-rose-600"></lucide-angular>
        </div>
      </div>
    </div>
  </div>

  <div class="grid grid-cols-1 xl:grid-cols-2 gap-6 mb-6">
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm">
      <div class="flex flex-col space-y-1 p-5 border-b border-zinc-100">
        <h3 class="text-sm font-semibold text-zinc-800 leading-none tracking-tight">Run Trend — Last 30 Days</h3>
      </div>
      <div class="p-5">
        <div *ngIf="!analytics()?.run_trend?.length" class="h-64 flex items-center justify-center text-zinc-400 text-sm">No trend data available yet.</div>
        <app-line-chart *ngIf="analytics()?.run_trend?.length" [data]="analytics()!.run_trend" class="block h-64"></app-line-chart>
      </div>
    </div>

    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm">
      <div class="flex flex-col space-y-1 p-5 border-b border-zinc-100">
        <h3 class="text-sm font-semibold text-zinc-800 leading-none tracking-tight">Top Failing Repositories</h3>
      </div>
      <div class="p-5">
        <div *ngIf="topFailingBars().length === 0" class="h-64 flex items-center justify-center text-zinc-400 text-sm">
          <div class="text-center">
            <lucide-angular [img]="icons.Activity" [size]="32" class="text-emerald-300 mx-auto mb-3"></lucide-angular>
            <p>No failing repos. Great work!</p>
          </div>
        </div>
        <app-bar-chart *ngIf="topFailingBars().length > 0" [data]="topFailingBars()"></app-bar-chart>
      </div>
    </div>
  </div>

  <div class="bg-white border border-zinc-200 rounded-lg shadow-sm mb-6">
    <div class="flex flex-col space-y-1 p-5 border-b border-zinc-100">
      <h3 class="text-sm font-semibold text-zinc-800 leading-none tracking-tight">Top Failing Workflows</h3>
    </div>
    <div class="p-5">
      <div *ngIf="topFailingWorkflowBars().length === 0" class="h-48 flex items-center justify-center text-zinc-400 text-sm">No failing workflows.</div>
      <app-bar-chart *ngIf="topFailingWorkflowBars().length > 0" [data]="topFailingWorkflowBars()"></app-bar-chart>
    </div>
  </div>

  <div class="bg-white border border-zinc-200 rounded-lg shadow-sm mb-6">
    <div class="flex flex-col space-y-1 p-5 border-b border-zinc-100">
      <h3 class="text-sm font-semibold text-zinc-800 leading-none tracking-tight">Run Outcomes ({{ completed().toLocaleString() }} completed)</h3>
    </div>
    <div class="p-5">
      <p *ngIf="completed() === 0" class="text-sm text-zinc-400 py-2">No completed runs yet.</p>
      <ng-container *ngIf="completed() > 0">
        <div class="flex h-3 w-full overflow-hidden rounded-full bg-zinc-100">
          <div class="bg-rose-500" [style.width.%]="failurePct()"></div>
          <div class="bg-emerald-500" [style.width.%]="successPct()"></div>
          <div class="bg-zinc-300" [style.width.%]="otherPct()"></div>
        </div>
        <div class="mt-3 flex flex-wrap gap-6 text-xs text-zinc-500">
          <span class="flex items-center gap-1.5"><span class="h-2 w-2 rounded-full bg-rose-500"></span>Failure {{ failurePct() | number: '1.1-1' }}% ({{ analytics()?.failure_count ?? 0 }})</span>
          <span class="flex items-center gap-1.5"><span class="h-2 w-2 rounded-full bg-emerald-500"></span>Success {{ successPct() | number: '1.1-1' }}% ({{ analytics()?.success_count ?? 0 }})</span>
          <span class="flex items-center gap-1.5"><span class="h-2 w-2 rounded-full bg-zinc-300"></span>Other {{ otherPct() | number: '1.1-1' }}% ({{ analytics()?.other_count ?? 0 }})</span>
        </div>
        <p class="mt-2 text-[11px] text-zinc-400">"Other" = cancelled, skipped, timed-out or startup-failure runs. In-progress / queued runs are excluded from all rates.</p>
      </ng-container>
    </div>
  </div>

  <div class="bg-white border border-zinc-200 rounded-lg shadow-sm">
    <div class="flex flex-col space-y-1 p-5 border-b border-zinc-100">
      <h3 class="text-sm font-semibold text-zinc-800 leading-none tracking-tight">AI Remediation</h3>
    </div>
    <div class="p-5">
      <div class="flex flex-wrap items-center gap-8 py-4">
        <div class="text-center">
          <p class="text-3xl font-bold text-zinc-800 tabular-nums">{{ analytics()?.remediations_raised ?? 0 }}</p>
          <p class="text-xs text-zinc-500 mt-1">PRs raised</p>
        </div>
        <div class="w-px h-12 bg-zinc-100"></div>
        <div class="text-center">
          <p class="text-3xl font-bold text-zinc-800 tabular-nums">{{ formatDuration(analytics()?.avg_analysis_seconds) }}</p>
          <p class="text-xs text-zinc-500 mt-1">Avg. time to fix suggestion</p>
        </div>
        <div class="w-px h-12 bg-zinc-100"></div>
        <div class="text-center">
          <p class="text-3xl font-bold text-zinc-800 tabular-nums">{{ formatDuration(analytics()?.mttr_seconds) }}</p>
          <p class="text-xs text-zinc-500 mt-1">MTTR (failure → PR)</p>
        </div>
      </div>
    </div>
  </div>
</div>
