// src/app/(dashboard)/dashboard/page.tsx
'use client'

import { useCallback } from 'react'
import { GitBranch, Activity, XCircle, Bot, AlertCircle } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { StatsCard } from '@/components/dashboard/stats-card'
import { RemediationFeed } from '@/components/dashboard/remediation-feed'
import { RunRow } from '@/components/workflows/run-row'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { SkeletonCard, SkeletonRow } from '@/components/ui/skeleton'
import { PageHeader } from '@/components/ui/page-header'
import { useWebSocket } from '@/hooks/useWebSocket'
import { useOrg } from '@/lib/org-context'
import {
  fetchCurrentUser,
  fetchWorkflowsByOrg,
  fetchRemediations,
  fetchRecentRuns,
} from '@/lib/api'
import type { WebSocketEvent, Remediation } from '@/types'
import { useQueryClient } from '@tanstack/react-query'

export default function DashboardPage() {
  const queryClient = useQueryClient()
  const { currentOrg, isLoading: orgsLoading } = useOrg()

  const { data: user } = useQuery({
    queryKey: ['user'],
    queryFn: fetchCurrentUser,
  })

  const { data: workflows = [], isLoading: workflowsLoading } = useQuery({
    queryKey: ['workflows', currentOrg],
    queryFn: () => fetchWorkflowsByOrg(currentOrg),
    enabled: Boolean(currentOrg),
  })

  const { data: recentRuns = [], isLoading: runsLoading } = useQuery({
    queryKey: ['runs'],
    queryFn: () => fetchRecentRuns(10),
  })

  const { data: remediations = [], isLoading: remediationsLoading } = useQuery({
    queryKey: ['remediations'],
    queryFn: fetchRemediations,
  })

  const handleWsMessage = useCallback(
    (event: WebSocketEvent) => {
      if (event.type === 'run_update') {
        queryClient.invalidateQueries({ queryKey: ['workflows'] })
        queryClient.invalidateQueries({ queryKey: ['runs'] })
      }
      if (event.type === 'remediation_created' || event.type === 'remediation_updated') {
        queryClient.invalidateQueries({ queryKey: ['remediations'] })
      }
    },
    [queryClient]
  )

  useWebSocket({ onMessage: handleWsMessage })

  const totalWorkflows = workflows.length
  const activeRuns = recentRuns.filter((r) => r.status === 'in_progress').length
  const failedToday = remediations.filter((r: Remediation) => {
    const runDate = new Date(r.created_at)
    const now = new Date()
    return (
      runDate.getUTCFullYear() === now.getUTCFullYear() &&
      runDate.getUTCMonth() === now.getUTCMonth() &&
      runDate.getUTCDate() === now.getUTCDate()
    )
  }).length
  const aiFixesRaised = remediations.filter(
    (r: Remediation) => r.status === 'pr_raised' && r.pr_url
  ).length

  const recentRemediations = remediations.slice(0, 3)

  const greeting = () => {
    const hour = new Date().getHours()
    if (hour < 12) return 'Good morning'
    if (hour < 17) return 'Good afternoon'
    return 'Good evening'
  }

  return (
    <div className="p-8">
      <PageHeader
        eyebrow="Overview"
        title={`${greeting()}${user?.name ? `, ${user.name.split(' ')[0]}` : ''}`}
        description="Here's what's happening across your pipelines."
      />

      {}
      <div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-8">
        {workflowsLoading || orgsLoading ? (
          <>
            {[...Array(4)].map((_, i) => (
              <SkeletonCard key={i} />
            ))}
          </>
        ) : (
          <>
            <StatsCard title="Total Workflows" value={totalWorkflows} icon={GitBranch} />
            <StatsCard
              title="Active Runs"
              value={activeRuns}
              icon={Activity}
              iconClassName="bg-emerald-50"
            />
            <StatsCard
              title="Failed Today"
              value={failedToday}
              icon={XCircle}
              iconClassName="bg-rose-50"
            />
            <StatsCard
              title="AI Fixes Raised"
              value={aiFixesRaised}
              icon={Bot}
              iconClassName="bg-amber-50"
            />
          </>
        )}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        {}
        <div className="xl:col-span-2">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle>Recent Workflow Runs</CardTitle>
                <a
                  href="/runs"
                  className="text-xs text-amber-600 hover:text-amber-700 font-medium"
                >
                  View all
                </a>
              </div>
            </CardHeader>
            <CardContent className="p-0">
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-zinc-100 bg-zinc-50">
                      <th className="text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4">
                        Workflow
                      </th>
                      <th className="text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4">
                        Repo
                      </th>
                      <th className="text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4">
                        Branch
                      </th>
                      <th className="text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4">
                        SHA
                      </th>
                      <th className="text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4">
                        Status
                      </th>
                      <th className="text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4">
                        Duration
                      </th>
                      <th className="text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4">
                        Started
                      </th>
                      <th className="py-3 px-4" />
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-zinc-100">
                    {runsLoading ? (
                      [...Array(5)].map((_, i) => (
                        <tr key={i}>
                          <td colSpan={8}>
                            <SkeletonRow />
                          </td>
                        </tr>
                      ))
                    ) : recentRuns.length === 0 ? (
                      <tr>
                        <td colSpan={8}>
                          <div className="flex flex-col items-center justify-center py-12 text-center">
                            <AlertCircle size={20} className="text-zinc-300 mb-2" />
                            <p className="text-sm text-zinc-400">
                              No workflow runs yet. Connect an organization in
                              Settings — runs appear here automatically as your
                              pipelines execute.
                            </p>
                          </div>
                        </td>
                      </tr>
                    ) : (
                      recentRuns.map((run) => (
                        <RunRow
                          key={run.id}
                          run={run}
                          showWorkflow={true}
                          showRepo={true}
                        />
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>
        </div>

        {}
        <div>
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle>Recent Remediations</CardTitle>
                <a
                  href="/remediation"
                  className="text-xs text-amber-600 hover:text-amber-700 font-medium"
                >
                  View all
                </a>
              </div>
            </CardHeader>
            <CardContent>
              {remediationsLoading ? (
                <div className="space-y-3">
                  {[...Array(3)].map((_, i) => (
                    <SkeletonCard key={i} />
                  ))}
                </div>
              ) : (
                <RemediationFeed remediations={recentRemediations} />
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

// angular-app/src/app/pages/dashboard.component.ts
import { Component, effect, signal } from '@angular/core'
import { CommonModule } from '@angular/common'
import { RouterLink } from '@angular/router'
import { LucideAngularModule, GitBranch, Activity, XCircle, Bot, AlertCircle, ExternalLink } from 'lucide-angular'
import { PageHeaderComponent } from '../shared/page-header.component'
import { BadgeComponent } from '../shared/badge.component'
import { RunRowComponent } from '../shared/run-row.component'
import { ApiService } from '../core/api.service'
import { OrgService } from '../core/org.service'
import { truncate, formatRelativeTime } from '../core/utils'
import type { WorkflowRun, Remediation, User } from '../core/types'

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, RouterLink, LucideAngularModule, PageHeaderComponent, BadgeComponent, RunRowComponent],
  templateUrl: './dashboard.component.html',
})
export class DashboardComponent {
  icons = { GitBranch, Activity, XCircle, Bot, AlertCircle, ExternalLink }
  truncate = truncate
  formatRelativeTime = formatRelativeTime

  user = signal<User | null>(null)
  workflows = signal<{ length: number }>({ length: 0 })
  recentRuns = signal<WorkflowRun[]>([])
  remediations = signal<Remediation[]>([])
  isLoading = signal(true)

  constructor(public org: OrgService, private api: ApiService) {
    effect(() => {
      if (this.org.currentOrg()) this.load()
    })
    this.api.fetchCurrentUser().then((u) => this.user.set(u)).catch(() => {})
  }

  async load() {
    this.isLoading.set(true)
    try {
      const [workflows, runsPage, remediations] = await Promise.all([
        this.api.fetchWorkflowsByOrg(this.org.currentOrg()),
        this.api.fetchRuns({ limit: 10 }),
        this.api.fetchRemediations(),
      ])
      this.workflows.set({ length: workflows.length })
      this.recentRuns.set(runsPage.runs)
      this.remediations.set(remediations)
    } finally {
      this.isLoading.set(false)
    }
  }

  greeting(): string {
    const hour = new Date().getHours()
    if (hour < 12) return 'Good morning'
    if (hour < 17) return 'Good afternoon'
    return 'Good evening'
  }

  activeRuns(): number {
    return this.recentRuns().filter((r) => r.status === 'in_progress').length
  }

  failedToday(): number {
    const now = new Date()
    return this.remediations().filter((r) => {
      const d = new Date(r.created_at)
      return d.getUTCFullYear() === now.getUTCFullYear() && d.getUTCMonth() === now.getUTCMonth() && d.getUTCDate() === now.getUTCDate()
    }).length
  }

  aiFixesRaised(): number {
    return this.remediations().filter((r) => r.status === 'pr_raised' && r.pr_url).length
  }

  recentRemediations(): Remediation[] {
    return this.remediations().slice(0, 3)
  }
}

<div class="p-8">
  <app-page-header eyebrow="Overview" [title]="greeting() + (user()?.name ? (', ' + user()!.name!.split(' ')[0]) : '')" description="Here's what's happening across your pipelines."></app-page-header>

  <div class="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-8">
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm p-5">
      <div class="flex items-start justify-between">
        <div class="flex-1 min-w-0">
          <p class="text-xs font-medium text-zinc-500 uppercase tracking-wider">Total Workflows</p>
          <p class="mt-2 text-2xl font-bold text-zinc-800 tabular-nums">{{ workflows().length }}</p>
        </div>
        <div class="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 bg-amber-50">
          <lucide-angular [img]="icons.GitBranch" [size]="20" class="text-amber-600"></lucide-angular>
        </div>
      </div>
    </div>
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm p-5">
      <div class="flex items-start justify-between">
        <div class="flex-1 min-w-0">
          <p class="text-xs font-medium text-zinc-500 uppercase tracking-wider">Active Runs</p>
          <p class="mt-2 text-2xl font-bold text-zinc-800 tabular-nums">{{ activeRuns() }}</p>
        </div>
        <div class="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 bg-emerald-50">
          <lucide-angular [img]="icons.Activity" [size]="20" class="text-current"></lucide-angular>
        </div>
      </div>
    </div>
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm p-5">
      <div class="flex items-start justify-between">
        <div class="flex-1 min-w-0">
          <p class="text-xs font-medium text-zinc-500 uppercase tracking-wider">Failed Today</p>
          <p class="mt-2 text-2xl font-bold text-zinc-800 tabular-nums">{{ failedToday() }}</p>
        </div>
        <div class="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 bg-rose-50">
          <lucide-angular [img]="icons.XCircle" [size]="20" class="text-current"></lucide-angular>
        </div>
      </div>
    </div>
    <div class="bg-white border border-zinc-200 rounded-lg shadow-sm p-5">
      <div class="flex items-start justify-between">
        <div class="flex-1 min-w-0">
          <p class="text-xs font-medium text-zinc-500 uppercase tracking-wider">AI Fixes Raised</p>
          <p class="mt-2 text-2xl font-bold text-zinc-800 tabular-nums">{{ aiFixesRaised() }}</p>
        </div>
        <div class="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 bg-amber-50">
          <lucide-angular [img]="icons.Bot" [size]="20" class="text-amber-600"></lucide-angular>
        </div>
      </div>
    </div>
  </div>

  <div class="grid grid-cols-1 xl:grid-cols-3 gap-6">
    <div class="xl:col-span-2">
      <div class="bg-white border border-zinc-200 rounded-lg shadow-sm">
        <div class="flex flex-col space-y-1 p-5 border-b border-zinc-100">
          <div class="flex items-center justify-between">
            <h3 class="text-sm font-semibold text-zinc-800 leading-none tracking-tight">Recent Workflow Runs</h3>
            <a routerLink="/runs" class="text-xs text-amber-600 hover:text-amber-700 font-medium">View all</a>
          </div>
        </div>
        <div class="p-0 overflow-x-auto">
          <table class="w-full table-fixed">
            <thead>
              <tr class="border-b border-zinc-100 bg-zinc-50">
                <th class="w-[26%] text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4 whitespace-nowrap">Workflow</th>
                <th class="w-[16%] text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4 whitespace-nowrap">Repo</th>
                <th class="w-[11%] text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4 whitespace-nowrap">Branch</th>
                <th class="w-[9%] text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4 whitespace-nowrap">SHA</th>
                <th class="w-[12%] text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4 whitespace-nowrap">Status</th>
                <th class="w-[10%] text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4 whitespace-nowrap">Duration</th>
                <th class="w-[12%] text-left text-xs font-semibold text-zinc-500 uppercase tracking-wider py-3 px-4 whitespace-nowrap">Started</th>
                <th class="w-[4%] py-3 px-4"></th>
              </tr>
            </thead>
            <tbody class="divide-y divide-zinc-100">
              <tr *ngIf="!isLoading() && recentRuns().length === 0">
                <td colspan="8">
                  <div class="flex flex-col items-center justify-center py-12 text-center">
                    <lucide-angular [img]="icons.AlertCircle" [size]="20" class="text-zinc-300 mb-2"></lucide-angular>
                    <p class="text-sm text-zinc-400">No workflow runs yet. Connect an organization in Settings — runs appear here automatically as your pipelines execute.</p>
                  </div>
                </td>
              </tr>
              <app-run-row *ngFor="let run of recentRuns()" [run]="run" [showWorkflow]="true" [showRepo]="true"></app-run-row>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div>
      <div class="bg-white border border-zinc-200 rounded-lg shadow-sm">
        <div class="flex flex-col space-y-1 p-5 border-b border-zinc-100">
          <div class="flex items-center justify-between">
            <h3 class="text-sm font-semibold text-zinc-800 leading-none tracking-tight">Recent Remediations</h3>
            <a routerLink="/remediation" class="text-xs text-amber-600 hover:text-amber-700 font-medium">View all</a>
          </div>
        </div>
        <div class="p-5">
          <div *ngIf="recentRemediations().length === 0" class="flex flex-col items-center justify-center py-8 text-center">
            <div class="w-10 h-10 bg-amber-50 rounded-full flex items-center justify-center mb-3">
              <lucide-angular [img]="icons.Bot" [size]="20" class="text-amber-500"></lucide-angular>
            </div>
            <p class="text-sm text-zinc-500">No remediations yet</p>
            <p class="text-xs text-zinc-400 mt-1">AI fixes will appear here</p>
          </div>
          <div *ngIf="recentRemediations().length > 0" class="space-y-3">
            <div *ngFor="let rem of recentRemediations()" class="flex items-start gap-3 p-3 rounded-lg border border-zinc-100 hover:border-zinc-200 hover:bg-zinc-50 transition-colors">
              <div class="w-7 h-7 bg-amber-50 rounded-md flex items-center justify-center flex-shrink-0 mt-0.5">
                <lucide-angular [img]="icons.Bot" [size]="14" class="text-amber-600"></lucide-angular>
              </div>
              <div class="flex-1 min-w-0">
                <div class="flex items-center gap-2 flex-wrap">
                  <span class="text-xs font-semibold text-zinc-700 truncate">{{ rem.repo_name }}</span>
                  <app-badge [status]="rem.status" [showDot]="false"></app-badge>
                </div>
                <p class="text-xs text-zinc-500 mt-0.5 leading-relaxed">{{ truncate(rem.root_cause, 80) }}</p>
                <div class="flex items-center gap-3 mt-1.5">
                  <span class="text-xs text-zinc-400">{{ formatRelativeTime(rem.created_at) }}</span>
                  <a *ngIf="rem.pr_url" [href]="rem.pr_url" target="_blank" rel="noopener noreferrer" class="inline-flex items-center gap-1 text-xs text-amber-600 hover:text-amber-700 font-medium">
                    View PR #{{ rem.pr_number }}
                    <lucide-angular [img]="icons.ExternalLink" [size]="10"></lucide-angular>
                  </a>
                  <a [routerLink]="['/remediation', rem.id]" class="text-xs text-zinc-400 hover:text-zinc-600">Details</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
