// src/app/(dashboard)/settings/page.tsx
'use client'

import { AlertCircle, ExternalLink, Github, Trash2 } from 'lucide-react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { fetchOrgs, removeOrg, getOrgInstallUrl } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { PageHeader } from '@/components/ui/page-header'
import { API_URL } from '@/lib/config'

export default function SettingsPage() {
  const queryClient = useQueryClient()

  const { data: orgs = [], isLoading } = useQuery({
    queryKey: ['orgs'],
    queryFn: fetchOrgs,
  })

  const removeMutation = useMutation({
    mutationFn: (login: string) => removeOrg(login),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orgs'] })
    },
  })

  const handleInstall = () => {
    
    window.location.href = getOrgInstallUrl()
  }

  return (
    <div className="p-8 max-w-3xl">
      <PageHeader
        title="Settings"
        description="Manage your connected GitHub organizations."
      />

      <Card>
        <CardHeader>
          <CardTitle>Connected Organizations</CardTitle>
          <CardDescription>
            Organizations tracked by Stagecraft via the Stagecraft GitHub App.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-2">
              {[...Array(2)].map((_, i) => (
                <div key={i} className="h-12 bg-zinc-50 rounded-lg animate-pulse" />
              ))}
            </div>
          ) : orgs.length === 0 ? (
            <div className="flex items-center gap-3 py-6 text-center justify-center text-zinc-400">
              <AlertCircle size={16} />
              <p className="text-sm">No organizations connected yet.</p>
            </div>
          ) : (
            <div className="space-y-2 mb-5">
              {orgs.map((org) => (
                <div
                  key={org.login}
                  className="flex items-center gap-3 p-3 bg-zinc-50 border border-zinc-100 rounded-lg"
                >
                  {org.avatar_url && (
                    
                    <img
                      src={org.avatar_url}
                      alt={org.login}
                      width={28}
                      height={28}
                      className="rounded-full"
                    />
                  )}
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-zinc-800 truncate">
                      {org.name || org.login}
                    </p>
                    <p className="text-xs text-zinc-400 truncate">@{org.login}</p>
                  </div>
                  <a
                    href={`https://github.com/${org.login}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-zinc-400 hover:text-zinc-600 transition-colors"
                  >
                    <ExternalLink size={13} />
                  </a>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="text-zinc-400 hover:text-rose-500 h-7 w-7"
                    onClick={() => removeMutation.mutate(org.login)}
                    disabled={removeMutation.isPending}
                    title="Remove organization"
                    aria-label={`Remove ${org.login}`}
                  >
                    <Trash2 size={13} />
                  </Button>
                </div>
              ))}
            </div>
          )}

          <div className="mt-4 pt-4 border-t border-zinc-100">
            <p className="text-xs text-zinc-500 mb-3">
              To connect a new organization, install the Stagecraft GitHub App on it.
              Once installed, it will appear here automatically.
            </p>
            <Button variant="primary" onClick={handleInstall} className="flex items-center gap-2">
              <Github size={15} />
              Install GitHub App
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// angular-app/src/app/pages/settings.component.ts
import { Component, OnInit, signal } from '@angular/core'
import { CommonModule } from '@angular/common'
import { LucideAngularModule, AlertCircle, ExternalLink, Github, Trash2 } from 'lucide-angular'
import { PageHeaderComponent } from '../shared/page-header.component'
import { ApiService } from '../core/api.service'
import type { Organization } from '../core/types'

@Component({
  selector: 'app-settings',
  standalone: true,
  imports: [CommonModule, LucideAngularModule, PageHeaderComponent],
  templateUrl: './settings.component.html',
})
export class SettingsComponent implements OnInit {
  icons = { AlertCircle, ExternalLink, Github, Trash2 }
  orgs = signal<Organization[]>([])
  isLoading = signal(true)
  removingLogin = signal<string | null>(null)

  constructor(private api: ApiService) {}

  async ngOnInit() {
    await this.load()
  }

  async load() {
    this.isLoading.set(true)
    try {
      this.orgs.set(await this.api.fetchOrgs())
    } finally {
      this.isLoading.set(false)
    }
  }

  async remove(login: string) {
    this.removingLogin.set(login)
    try {
      await this.api.removeOrg(login)
      await this.load()
    } finally {
      this.removingLogin.set(null)
    }
  }

  install() {
    window.location.href = this.api.getOrgInstallUrl()
  }
}

<div class="p-8 max-w-3xl">
  <app-page-header title="Settings" description="Manage your connected GitHub organizations."></app-page-header>

  <div class="bg-white border border-zinc-200 rounded-lg shadow-sm dark:bg-zinc-900 dark:border-zinc-800">
    <div class="flex flex-col space-y-1 p-5 border-b border-zinc-100 dark:border-zinc-800">
      <h3 class="text-sm font-semibold text-zinc-800 dark:text-zinc-100 leading-none tracking-tight">Connected Organizations</h3>
      <p class="text-xs text-zinc-500 dark:text-zinc-400">Organizations tracked by Stagecraft via the Stagecraft GitHub App.</p>
    </div>
    <div class="p-5">
      <div *ngIf="isLoading()" class="space-y-2">
        <div class="h-12 bg-zinc-50 rounded-lg animate-pulse"></div>
        <div class="h-12 bg-zinc-50 rounded-lg animate-pulse"></div>
      </div>

      <div *ngIf="!isLoading() && orgs().length === 0" class="flex items-center gap-3 py-6 text-center justify-center text-zinc-400">
        <lucide-angular [img]="icons.AlertCircle" [size]="16"></lucide-angular>
        <p class="text-sm">No organizations connected yet.</p>
      </div>

      <div *ngIf="!isLoading() && orgs().length > 0" class="space-y-2 mb-5">
        <div *ngFor="let org of orgs()" class="flex items-center gap-3 p-3 bg-zinc-50 border border-zinc-100 rounded-lg">
          <img *ngIf="org.avatar_url" [src]="org.avatar_url" [alt]="org.login" width="28" height="28" class="rounded-full" />
          <div class="flex-1 min-w-0">
            <p class="text-sm font-medium text-zinc-800 truncate">{{ org.name || org.login }}</p>
            <p class="text-xs text-zinc-400 truncate">&#64;{{ org.login }}</p>
          </div>
          <a [href]="'https://github.com/' + org.login" target="_blank" rel="noopener noreferrer" class="text-zinc-400 hover:text-zinc-600 transition-colors">
            <lucide-angular [img]="icons.ExternalLink" [size]="13"></lucide-angular>
          </a>
          <button
            (click)="remove(org.login)"
            [disabled]="removingLogin() === org.login"
            title="Remove organization"
            [attr.aria-label]="'Remove ' + org.login"
            class="inline-flex items-center justify-center h-7 w-7 rounded-md text-zinc-400 hover:text-rose-500 disabled:opacity-50"
          >
            <lucide-angular [img]="icons.Trash2" [size]="13"></lucide-angular>
          </button>
        </div>
      </div>

      <div class="mt-4 pt-4 border-t border-zinc-100">
        <p class="text-xs text-zinc-500 mb-3">
          To connect a new organization, install the Stagecraft GitHub App on it. Once installed, it will appear here automatically.
        </p>
        <button (click)="install()" class="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-md bg-amber-500 text-white hover:bg-amber-600 transition-colors">
          <lucide-angular [img]="icons.Github" [size]="15"></lucide-angular>
          Install GitHub App
        </button>
      </div>
    </div>
  </div>
</div>
