// angular-app/src/app/pages/optimization.component.ts
import { Component, computed, effect, signal } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { LucideAngularModule, RefreshCw, Clock, CheckCircle2, XCircle } from 'lucide-angular'
import { PageHeaderComponent } from '../shared/page-header.component'
import { BadgeComponent } from '../shared/badge.component'
import { ApiService } from '../core/api.service'
import { OrgService } from '../core/org.service'
import type { Workflow, OptimizationRecommendation } from '../core/types'

function formatDuration(seconds: number): string {
  const sign = seconds < 0 ? '-' : ''
  const abs = Math.abs(seconds)
  if (abs < 60) return `${sign}${abs}s`
  return `${sign}${Math.floor(abs / 60)}m ${abs % 60}s`
}

@Component({
  selector: 'app-optimization',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule, PageHeaderComponent, BadgeComponent],
  templateUrl: './optimization.component.html',
})
export class OptimizationComponent {
  icons = { RefreshCw, Clock, CheckCircle2, XCircle }
  formatDuration = formatDuration

  workflows = signal<Workflow[]>([])
  selectedRepo = signal('')
  selectedWorkflow = signal('')
  recommendations = signal<OptimizationRecommendation[]>([])
  analyzing = signal(false)

  repos = computed(() => Array.from(new Set(this.workflows().map((w) => w.repo_name))).sort())
  repoWorkflows = computed(() => this.workflows().filter((w) => w.repo_name === this.selectedRepo()))

  constructor(public org: OrgService, private api: ApiService) {
    effect(() => {
      if (this.org.currentOrg()) this.init()
    })
  }

  async init() {
    const workflows = await this.api.fetchWorkflowsByOrg(this.org.currentOrg())
    this.workflows.set(workflows)
    const repos = Array.from(new Set(workflows.map((w) => w.repo_name))).sort()
    if (repos.length > 0 && !this.selectedRepo()) this.selectedRepo.set(repos[0])
    const repoWfs = workflows.filter((w) => w.repo_name === this.selectedRepo())
    if (repoWfs.length > 0 && !this.selectedWorkflow()) this.selectedWorkflow.set(repoWfs[0].path)
    await this.loadRecommendations()
  }

  onRepoChange(repo: string) {
    this.selectedRepo.set(repo)
    this.selectedWorkflow.set('')
    const repoWfs = this.workflows().filter((w) => w.repo_name === repo)
    if (repoWfs.length > 0) this.selectedWorkflow.set(repoWfs[0].path)
    this.loadRecommendations()
  }

  async loadRecommendations() {
    if (!this.selectedRepo()) return
    this.recommendations.set(await this.api.fetchOptimizationRecommendations(this.org.currentOrg(), this.selectedRepo()))
  }

  async analyze() {
    this.analyzing.set(true)
    try {
      await this.api.analyzeOptimization(this.org.currentOrg(), this.selectedRepo(), this.selectedWorkflow())
      await this.loadRecommendations()
    } finally {
      this.analyzing.set(false)
    }
  }

  async accept(id: string) {
    await this.api.acceptRecommendation(id)
    await this.loadRecommendations()
  }

  async reject(id: string) {
    await this.api.rejectRecommendation(id)
    await this.loadRecommendations()
  }
}

<div class="p-8">
  <app-page-header eyebrow="Quality" title="Optimization" description="Bottleneck analysis, parallelization opportunities, and simulated time savings.">
    <ng-container actions>
      <select *ngIf="repos().length > 1" [ngModel]="selectedRepo()" (ngModelChange)="onRepoChange($event)" class="text-sm border border-zinc-200 rounded-md bg-white text-zinc-700 px-3 py-2">
        <option *ngFor="let repo of repos()" [value]="repo">{{ repo }}</option>
      </select>
      <select *ngIf="repoWorkflows().length > 1" [ngModel]="selectedWorkflow()" (ngModelChange)="selectedWorkflow.set($event)" class="text-sm border border-zinc-200 rounded-md bg-white text-zinc-700 px-3 py-2">
        <option *ngFor="let w of repoWorkflows()" [value]="w.path">{{ w.name }}</option>
      </select>
      <button (click)="analyze()" [disabled]="analyzing() || !selectedWorkflow()" class="flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-md bg-amber-500 text-white hover:bg-amber-600 disabled:opacity-50 transition-colors">
        <lucide-angular [img]="icons.RefreshCw" [size]="14" [class.animate-spin]="analyzing()"></lucide-angular>
        Analyze
      </button>
    </ng-container>
  </app-page-header>

  <div *ngIf="recommendations().length === 0" class="bg-white border border-zinc-200 rounded-lg shadow-sm">
    <div class="py-12 text-center text-sm text-zinc-400">
      No optimization recommendations yet. Analysis needs a completed dependency graph (Dependency Graph tab) and job timing data (a few completed runs) for this workflow first.
    </div>
  </div>

  <div *ngIf="recommendations().length > 0" class="space-y-4">
    <div *ngFor="let rec of recommendations()" class="bg-white border border-zinc-200 rounded-lg shadow-sm">
      <div class="py-5 px-5">
        <div class="flex items-start justify-between gap-4">
          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-2 mb-1">
              <app-badge [status]="rec.status === 'proposed' ? 'pending' : rec.status" [label]="rec.recommendation_type.replace('_', ' ')"></app-badge>
              <span class="text-xs text-zinc-400">confidence {{ rec.confidence_score }}%</span>
            </div>
            <p class="text-sm text-zinc-700">{{ rec.description }}</p>
            <div class="flex items-center gap-3 mt-2">
              <div class="flex items-center gap-1.5 text-xs text-emerald-600">
                <lucide-angular [img]="icons.Clock" [size]="12"></lucide-angular>
                Estimated savings: {{ formatDuration(rec.estimated_time_savings_seconds) }}
              </div>
              <button *ngIf="rec.proposed_yaml_diff" (click)="toggleDiff(rec.id)" class="flex items-center gap-1 text-xs text-zinc-500 hover:text-zinc-700">
                <lucide-angular [img]="isDiffOpen(rec.id) ? icons.ChevronUp : icons.ChevronDown" [size]="12"></lucide-angular>
                {{ isDiffOpen(rec.id) ? 'Hide' : 'Show' }} proposed change
              </button>
            </div>
            <a *ngIf="rec.pr_url" [href]="rec.pr_url" target="_blank" rel="noopener noreferrer" class="inline-flex items-center gap-1.5 mt-2 text-xs font-medium text-emerald-600 hover:text-emerald-700">
              <lucide-angular [img]="icons.ExternalLink" [size]="12"></lucide-angular>
              View PR {{ rec.pr_number ? '#' + rec.pr_number : '' }}
            </a>
          </div>
          <div *ngIf="rec.status === 'proposed'" class="flex items-center gap-2 flex-shrink-0">
            <button (click)="accept(rec.id)" [disabled]="accepting() === rec.id" class="flex items-center gap-1 text-xs font-medium text-emerald-600 hover:text-emerald-700 px-2 py-1 rounded border border-emerald-200 hover:bg-emerald-50 disabled:opacity-50">
              <lucide-angular [img]="icons.CheckCircle2" [size]="13" [class.animate-spin]="accepting() === rec.id"></lucide-angular>
              {{ accepting() === rec.id ? 'Raising PR…' : 'Accept' }}
            </button>
            <button (click)="reject(rec.id)" [disabled]="accepting() === rec.id" class="flex items-center gap-1 text-xs font-medium text-zinc-500 hover:text-rose-600 px-2 py-1 rounded border border-zinc-200 hover:bg-rose-50 disabled:opacity-50">
              <lucide-angular [img]="icons.XCircle" [size]="13"></lucide-angular> Reject
            </button>
          </div>
        </div>
      </div>

      <div *ngIf="isDiffOpen(rec.id) && rec.proposed_yaml_diff" class="px-5 pb-5">
        <div class="bg-zinc-900 rounded-lg overflow-hidden">
          <div class="flex items-center justify-between px-4 py-2.5 border-b border-zinc-700">
            <span class="text-xs text-zinc-400 font-mono">{{ rec.workflow_file }}</span>
            <span *ngIf="addedLineCount(rec) > 0" class="text-xs text-emerald-400">{{ addedLineCount(rec) }} line{{ addedLineCount(rec) !== 1 ? 's' : '' }} changed</span>
          </div>
          <pre class="p-5 text-xs text-zinc-300 font-mono leading-relaxed overflow-x-auto max-h-[420px]"><code
            ><ng-container *ngFor="let line of diffFor(rec)"><span [class.bg-emerald-900]="line.kind === 'added'" [class.border-l-2]="line.kind === 'added'" [class.border-emerald-500]="line.kind === 'added'" [class.pl-2]="line.kind === 'added'" [class.-ml-2]="line.kind === 'added'" class="block">{{ line.text }}</span></ng-container></code></pre>
        </div>
      </div>
    </div>
  </div>
</div>

// src/app/(dashboard)/optimization/page.tsx
'use client'

import { useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { RefreshCw, Clock, CheckCircle2, XCircle } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { PageHeader } from '@/components/ui/page-header'
import { useOrg } from '@/lib/org-context'
import {
  fetchWorkflowsByOrg,
  analyzeOptimization,
  fetchOptimizationRecommendations,
  acceptRecommendation,
  rejectRecommendation,
} from '@/lib/api'

function formatDuration(seconds: number): string {
  const sign = seconds < 0 ? '-' : ''
  const abs = Math.abs(seconds)
  if (abs < 60) return `${sign}${abs}s`
  return `${sign}${Math.floor(abs / 60)}m ${abs % 60}s`
}

export default function OptimizationPage() {
  const [selectedRepo, setSelectedRepo] = useState('')
  const [selectedWorkflow, setSelectedWorkflow] = useState('')
  const queryClient = useQueryClient()
  const { currentOrg } = useOrg()

  const { data: workflows = [] } = useQuery({
    queryKey: ['workflows', currentOrg],
    queryFn: () => fetchWorkflowsByOrg(currentOrg),
    enabled: Boolean(currentOrg),
  })
  const repos = useMemo(() => Array.from(new Set(workflows.map((w) => w.repo_name))).sort(), [workflows])
  useEffect(() => {
    if (repos.length > 0 && !selectedRepo) setSelectedRepo(repos[0])
  }, [repos, selectedRepo])
  const currentRepo = selectedRepo || repos[0] || ''

  const repoWorkflows = useMemo(
    () => workflows.filter((w) => w.repo_name === currentRepo),
    [workflows, currentRepo]
  )
  useEffect(() => {
    if (repoWorkflows.length > 0 && !selectedWorkflow) setSelectedWorkflow(repoWorkflows[0].path)
  }, [repoWorkflows, selectedWorkflow])
  const currentWorkflow = selectedWorkflow || repoWorkflows[0]?.path || ''

  const { data: recommendations = [] } = useQuery({
    queryKey: ['optimization-recommendations', currentOrg, currentRepo],
    queryFn: () => fetchOptimizationRecommendations(currentOrg, currentRepo),
    enabled: Boolean(currentOrg) && Boolean(currentRepo),
  })

  const analyze = useMutation({
    mutationFn: () => analyzeOptimization(currentOrg, currentRepo, currentWorkflow),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['optimization-recommendations', currentOrg, currentRepo] }),
  })

  const accept = useMutation({
    mutationFn: (id: string) => acceptRecommendation(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['optimization-recommendations', currentOrg, currentRepo] }),
  })

  const reject = useMutation({
    mutationFn: (id: string) => rejectRecommendation(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['optimization-recommendations', currentOrg, currentRepo] }),
  })

  return (
    <div className="p-8">
      <PageHeader
        eyebrow="Quality"
        title="Optimization"
        description="Bottleneck analysis, parallelization opportunities, and simulated time savings."
        actions={
          <>
            {repos.length > 1 && (
              <select
                value={currentRepo}
                onChange={(e) => { setSelectedRepo(e.target.value); setSelectedWorkflow('') }}
                className="text-sm border border-zinc-200 rounded-md bg-white text-zinc-700 px-3 py-2"
              >
                {repos.map((repo) => <option key={repo} value={repo}>{repo}</option>)}
              </select>
            )}
            {repoWorkflows.length > 1 && (
              <select
                value={currentWorkflow}
                onChange={(e) => setSelectedWorkflow(e.target.value)}
                className="text-sm border border-zinc-200 rounded-md bg-white text-zinc-700 px-3 py-2"
              >
                {repoWorkflows.map((w) => <option key={w.path} value={w.path}>{w.name}</option>)}
              </select>
            )}
            <button
              onClick={() => analyze.mutate()}
              disabled={analyze.isPending || !currentWorkflow}
              className="flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-md bg-amber-500 text-white hover:bg-amber-600 disabled:opacity-50 transition-colors"
            >
              <RefreshCw size={14} className={analyze.isPending ? 'animate-spin' : ''} />
              Analyze
            </button>
          </>
        }
      />

      {recommendations.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center text-sm text-zinc-400">
            No optimization recommendations yet. Analysis needs a completed dependency graph
            (Dependency Graph tab) and job timing data (a few completed runs) for this workflow first.
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {recommendations.map((rec) => (
            <Card key={rec.id}>
              <CardContent className="py-5">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <Badge status={rec.status === 'proposed' ? 'pending' : rec.status} label={rec.recommendation_type.replace('_', ' ')} />
                      <span className="text-xs text-zinc-400">confidence {rec.confidence_score}%</span>
                    </div>
                    <p className="text-sm text-zinc-700 dark:text-zinc-200">{rec.description}</p>
                    <div className="flex items-center gap-1.5 mt-2 text-xs text-emerald-600">
                      <Clock size={12} />
                      Estimated savings: {formatDuration(rec.estimated_time_savings_seconds)}
                    </div>
                  </div>
                  {rec.status === 'proposed' && (
                    <div className="flex items-center gap-2 flex-shrink-0">
                      <button
                        onClick={() => accept.mutate(rec.id)}
                        className="flex items-center gap-1 text-xs font-medium text-emerald-600 hover:text-emerald-700 px-2 py-1 rounded border border-emerald-200 hover:bg-emerald-50"
                      >
                        <CheckCircle2 size={13} /> Accept
                      </button>
                      <button
                        onClick={() => reject.mutate(rec.id)}
                        className="flex items-center gap-1 text-xs font-medium text-zinc-500 hover:text-rose-600 px-2 py-1 rounded border border-zinc-200 hover:bg-rose-50"
                      >
                        <XCircle size={13} /> Reject
                      </button>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
